//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PqnASPLesson9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pqnKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pqnKhoa()
        {
            this.pqnSinhVien = new HashSet<pqnSinhVien>();
        }
    
        public string PqnMaKH { get; set; }
        public string PqnTenKH { get; set; }
        public Nullable<bool> PqnTrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pqnSinhVien> pqnSinhVien { get; set; }
    }
}
