//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PqnASPLesson9.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Pqnk22CNTT1lesson9Entities : DbContext
    {
        public Pqnk22CNTT1lesson9Entities()
            : base("name=Pqnk22CNTT1lesson9Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<pqnKhoa> pqnKhoa { get; set; }
        public virtual DbSet<pqnSinhVien> pqnSinhVien { get; set; }
    }
}
