//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PqnASPLesson9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pqnSinhVien
    {
        public string PqnMaSV { get; set; }
        public string PqnHoSV { get; set; }
        public string PqnTenSV { get; set; }
        public Nullable<System.DateTime> PqnNgaySinh { get; set; }
        public Nullable<bool> PqnPhai { get; set; }
        public string PqnPhone { get; set; }
        public string PqnEmail { get; set; }
        public string PqnMaKH { get; set; }
    
        public virtual pqnKhoa pqnKhoa { get; set; }
    }
}
